name       : mujs
version    : 1.0.7
release    : 1
source     :
    - https://github.com/ArtifexSoftware/mujs/archive/1.0.7.tar.gz : 9081244e070381300acaa5bf306a8b8b6f6231932ef4dca122992d3f6d243446
license    : ISC
homepage   : https://mujs.com/
component  : programming.library
summary    : An embeddable Javascript interpreter in C
libsplit   : no
description: |
    MuJS is a lightweight Javascript interpreter designed for embedding in other software to extend them with scripting capabilities.
build      : |
    %make
install    : |
    %make_install install-shared prefix=%PREFIX% libdir=%libdir%

    # Remove the static library
    rm -v $installdir/usr/lib64/lib*.a
