name       : mujs
version    : 1.3.0
release    : 3
source     :
    - https://github.com/ArtifexSoftware/mujs/archive/refs/tags/1.3.0.tar.gz : e22a087e6c00dc37a5a9f98ddef92c3ea5a142786a53deffe4a9f39050b811f5
license    : ISC
homepage   : https://mujs.com/
component  : programming.library
summary    : An embeddable Javascript interpreter in C
libsplit   : no
description: |
    MuJS is a lightweight Javascript interpreter designed for embedding in other software to extend them with scripting capabilities.
build      : |
    %make
install    : |
    %make_install install-shared prefix=%PREFIX% libdir=%libdir%

    # Remove the static library
    rm -v $installdir/usr/lib64/lib*.a
